[2022-12-04T18:28:29.316+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: predict_data.predict_data scheduled__2022-12-03T00:00:00+00:00 [queued]>
[2022-12-04T18:28:29.323+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: predict_data.predict_data scheduled__2022-12-03T00:00:00+00:00 [queued]>
[2022-12-04T18:28:29.324+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-04T18:28:29.325+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-04T18:28:29.326+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-04T18:28:29.338+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): predict_data> on 2022-12-03 00:00:00+00:00
[2022-12-04T18:28:29.345+0000] {standard_task_runner.py:55} INFO - Started process 8040 to run task
[2022-12-04T18:28:29.351+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'predict_data', 'predict_data', 'scheduled__2022-12-03T00:00:00+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/predict_values.py', '--cfg-path', '/tmp/tmpzhxrpoym']
[2022-12-04T18:28:29.355+0000] {standard_task_runner.py:83} INFO - Job 97: Subtask predict_data
[2022-12-04T18:28:29.420+0000] {task_command.py:389} INFO - Running <TaskInstance: predict_data.predict_data scheduled__2022-12-03T00:00:00+00:00 [running]> on host c7dedbf79ea9
[2022-12-04T18:28:29.481+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=predict_data
AIRFLOW_CTX_TASK_ID=predict_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-03T00:00:00+00:00
[2022-12-04T18:28:29.574+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  "X does not have valid feature names, but"

[2022-12-04T18:28:29.592+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-12-04T18:28:29.612+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=predict_data, task_id=predict_data, execution_date=20221203T000000, start_date=20221204T182829, end_date=20221204T182829
[2022-12-04T18:28:29.647+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-04T18:28:29.669+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
